In [1]:
import numpy as np

In [10]:
A = np.random.randint(3,size=(2,3))
B = np.random.randint(3,size=(3,4))

In [11]:
print(A)

[[2 0 0]
 [0 1 2]]


In [12]:
print(B)

[[0 0 0 1]
 [1 2 2 0]
 [2 0 0 2]]


In [14]:
print(A.dot(B))

[[0 0 0 2]
 [5 2 2 4]]


In [15]:
import tensorflow as tf

In [16]:
TA = tf.constant(A)

In [17]:
TB = tf.constant(B)

In [18]:
se = tf.Session()

In [19]:
print(se.run([TA,TB]))

[array([[2, 0, 0],
       [0, 1, 2]]), array([[0, 0, 0, 1],
       [1, 2, 2, 0],
       [2, 0, 0, 2]])]


In [27]:
print(se.run(tf.matmul(TA,TB)))

[[0 0 0 2]
 [5 2 2 4]]
